"""Shared chess-puzzle move validation.

Lichess puzzle data stores one principal variation.  A position can still have
multiple legal mating moves.  The old bots handled that inconsistently: Rush
and Survival had local mate-in-one exceptions while RP/Practice/Daily compared
only against the single stored UCI move.

This module keeps parsing and the alternative-mate rule identical everywhere.
It intentionally does *not* guess that a merely legal move is tactically equal:
without an engine that would create false positives.  What we can prove locally
is accepted: the stored solution move, or any legal submitted move that ends the
game by checkmate immediately.
"""

from __future__ import annotations

import re

import chess


_ANNOTATION_RE = re.compile(r"[!?]{1,2}$")


def clean_move_text(text) -> str:
    value = str(text or "").strip()
    if value.startswith("!"):
        value = value[1:].strip()
    value = _ANNOTATION_RE.sub("", value)
    value = re.sub(r'^([KQRBN])\s+([a-h][1-8][+#]?)$', r'\1\2', value, flags=re.IGNORECASE)
    return value.strip()


def normalize_move_text(text) -> str:
    """Normalize SAN-ish input for case-insensitive comparison.

    Capture/check/mate markers are optional, castling accepts zeroes or letter O, and
    human annotation suffixes are ignored.  The normalized form is used only
    for matching against legal moves generated by python-chess, so legality is
    still enforced by the board.
    """
    value = clean_move_text(text)
    value = "".join(value.split()).casefold()
    value = value.replace("0-0-0", "o-o-o").replace("0-0", "o-o")
    # SAN's capture marker is optional; source/disambiguation remain mandatory.
    value = value.replace('x', '')
    while value.endswith(("+", "#")):
        value = value[:-1]
    # Accept common promotion shorthand such as e8Q as equivalent to e8=Q.
    if re.fullmatch(r"[a-h]{1,2}[18][qrbn]", value):
        value = value[:-1] + "=" + value[-1]
    return value


def parse_legal_move(board, submitted):
    """Return the submitted legal move (SAN or UCI) or ``None``."""
    normalized = normalize_move_text(submitted)
    if not normalized:
        return None

    # Standard SAN/UCI needs no scan of every legal move. Keep the normalized
    # comparison so python-chess's permissive SAN parser cannot broaden input.
    raw = clean_move_text(submitted)
    try:
        if re.fullmatch(r"[a-h][1-8][a-h][1-8][qrbn]?", raw.casefold()):
            return board.parse_uci(raw.casefold())
        candidate = board.parse_san(raw)
        if candidate in board.legal_moves and normalize_move_text(board.san(candidate)) == normalized:
            return candidate
    except ValueError:
        pass

    # Compare to SAN generated for every legal move.  This gives us robust,
    # case-insensitive SAN without trusting parse_san on non-standard casing.
    matches = []
    for legal_move in board.legal_moves:
        try:
            if normalize_move_text(board.san(legal_move)) == normalized:
                matches.append(legal_move)
        except Exception:
            continue
    if len(matches) == 1:
        return matches[0]
    if matches:
        return None

    # UCI input is naturally lowercase, e.g. g7h7 or a7a8q.
    try:
        uci = clean_move_text(submitted).replace(" ", "").casefold()
        move = board.parse_uci(uci)
    except Exception:
        return None
    return move if move in board.legal_moves else None


def _expected_uci(expected) -> str:
    if isinstance(expected, dict):
        return str(expected.get("uci") or "").strip().casefold()
    return str(expected or "").strip().casefold()


def match_solution_move(board, submitted, expected, *, accept_alternative_mate=True):
    """Return ``(accepted, move, kind)`` for one puzzle move.

    ``kind`` is one of ``principal``, ``alternative_checkmate``, ``wrong`` or
    ``illegal``.  The board is never mutated.
    """
    move = parse_legal_move(board, submitted)
    if move is None:
        return False, None, "illegal"

    expected_uci = _expected_uci(expected)
    if expected_uci and move.uci().casefold() == expected_uci:
        return True, move, "principal"

    if accept_alternative_mate:
        trial = board.copy(stack=False)
        try:
            trial.push(move)
        except Exception:
            return False, None, "illegal"
        if trial.is_checkmate():
            return True, move, "alternative_checkmate"

    return False, move, "wrong"


def move_is_solution(board, submitted, expected, *, accept_alternative_mate=True) -> bool:
    return match_solution_move(
        board,
        submitted,
        expected,
        accept_alternative_mate=accept_alternative_mate,
    )[0]
